image: hub.byted.org/maven3-jdk-8:6afdcb40bff3b6dc59baa8598707d4be

stages:
  - build

build:
  stage: build
  script:
    # TODO(huweihua): remove skipTests when we can pass unitTest.
    - echo "registry = 'https://registry.npm.taobao.org'" > ~/.npmrc
    - export https_proxy=bj-rd-proxy.byted.org:3128 http_proxy=http://bj-rd-proxy.byted.org:3128
    - mvn clean package -DskipTests -Pinclude-hadoop -T 1C
#  only:
#    - merge_requests
  tags:
    - inf-compute-stream
