image: hub.byted.org/maven3-jdk-8:6afdcb40bff3b6dc59baa8598707d4be

stages:
  - build

build:
  stage: build
  script:
    # TODO(huweihua): remove skipTests when we can pass unitTest.
    - export https_proxy=http://bj-rd-proxy.byted.org:3128
    - mvn clean package -DskipTests -Pinclude-hadoop
#  only:
#    - merge_requests
  tags:
    - inf-compute-stream
