/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.flink.connectors.loghouse.service;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-03-10")
public class Key implements org.apache.thrift.TBase<Key, Key._Fields>, java.io.Serializable, Cloneable, Comparable<Key> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Key");

  private static final org.apache.thrift.protocol.TField PARTITION_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("partitionKey", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CLUSTERING_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("clusteringKey", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new KeyStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new KeyTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String partitionKey; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String clusteringKey; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PARTITION_KEY((short)1, "partitionKey"),
    CLUSTERING_KEY((short)2, "clusteringKey");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PARTITION_KEY
          return PARTITION_KEY;
        case 2: // CLUSTERING_KEY
          return CLUSTERING_KEY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PARTITION_KEY, new org.apache.thrift.meta_data.FieldMetaData("partitionKey", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CLUSTERING_KEY, new org.apache.thrift.meta_data.FieldMetaData("clusteringKey", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Key.class, metaDataMap);
  }

  public Key() {
  }

  public Key(
    java.lang.String partitionKey,
    java.lang.String clusteringKey)
  {
    this();
    this.partitionKey = partitionKey;
    this.clusteringKey = clusteringKey;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Key(Key other) {
    if (other.isSetPartitionKey()) {
      this.partitionKey = other.partitionKey;
    }
    if (other.isSetClusteringKey()) {
      this.clusteringKey = other.clusteringKey;
    }
  }

  public Key deepCopy() {
    return new Key(this);
  }

  @Override
  public void clear() {
    this.partitionKey = null;
    this.clusteringKey = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPartitionKey() {
    return this.partitionKey;
  }

  public Key setPartitionKey(@org.apache.thrift.annotation.Nullable java.lang.String partitionKey) {
    this.partitionKey = partitionKey;
    return this;
  }

  public void unsetPartitionKey() {
    this.partitionKey = null;
  }

  /** Returns true if field partitionKey is set (has been assigned a value) and false otherwise */
  public boolean isSetPartitionKey() {
    return this.partitionKey != null;
  }

  public void setPartitionKeyIsSet(boolean value) {
    if (!value) {
      this.partitionKey = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getClusteringKey() {
    return this.clusteringKey;
  }

  public Key setClusteringKey(@org.apache.thrift.annotation.Nullable java.lang.String clusteringKey) {
    this.clusteringKey = clusteringKey;
    return this;
  }

  public void unsetClusteringKey() {
    this.clusteringKey = null;
  }

  /** Returns true if field clusteringKey is set (has been assigned a value) and false otherwise */
  public boolean isSetClusteringKey() {
    return this.clusteringKey != null;
  }

  public void setClusteringKeyIsSet(boolean value) {
    if (!value) {
      this.clusteringKey = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PARTITION_KEY:
      if (value == null) {
        unsetPartitionKey();
      } else {
        setPartitionKey((java.lang.String)value);
      }
      break;

    case CLUSTERING_KEY:
      if (value == null) {
        unsetClusteringKey();
      } else {
        setClusteringKey((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PARTITION_KEY:
      return getPartitionKey();

    case CLUSTERING_KEY:
      return getClusteringKey();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PARTITION_KEY:
      return isSetPartitionKey();
    case CLUSTERING_KEY:
      return isSetClusteringKey();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Key)
      return this.equals((Key)that);
    return false;
  }

  public boolean equals(Key that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_partitionKey = true && this.isSetPartitionKey();
    boolean that_present_partitionKey = true && that.isSetPartitionKey();
    if (this_present_partitionKey || that_present_partitionKey) {
      if (!(this_present_partitionKey && that_present_partitionKey))
        return false;
      if (!this.partitionKey.equals(that.partitionKey))
        return false;
    }

    boolean this_present_clusteringKey = true && this.isSetClusteringKey();
    boolean that_present_clusteringKey = true && that.isSetClusteringKey();
    if (this_present_clusteringKey || that_present_clusteringKey) {
      if (!(this_present_clusteringKey && that_present_clusteringKey))
        return false;
      if (!this.clusteringKey.equals(that.clusteringKey))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPartitionKey()) ? 131071 : 524287);
    if (isSetPartitionKey())
      hashCode = hashCode * 8191 + partitionKey.hashCode();

    hashCode = hashCode * 8191 + ((isSetClusteringKey()) ? 131071 : 524287);
    if (isSetClusteringKey())
      hashCode = hashCode * 8191 + clusteringKey.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Key other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetPartitionKey()).compareTo(other.isSetPartitionKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPartitionKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.partitionKey, other.partitionKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetClusteringKey()).compareTo(other.isSetClusteringKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClusteringKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.clusteringKey, other.clusteringKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Key(");
    boolean first = true;

    sb.append("partitionKey:");
    if (this.partitionKey == null) {
      sb.append("null");
    } else {
      sb.append(this.partitionKey);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("clusteringKey:");
    if (this.clusteringKey == null) {
      sb.append("null");
    } else {
      sb.append(this.clusteringKey);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class KeyStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public KeyStandardScheme getScheme() {
      return new KeyStandardScheme();
    }
  }

  private static class KeyStandardScheme extends org.apache.thrift.scheme.StandardScheme<Key> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Key struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PARTITION_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.partitionKey = iprot.readString();
              struct.setPartitionKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CLUSTERING_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.clusteringKey = iprot.readString();
              struct.setClusteringKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Key struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.partitionKey != null) {
        oprot.writeFieldBegin(PARTITION_KEY_FIELD_DESC);
        oprot.writeString(struct.partitionKey);
        oprot.writeFieldEnd();
      }
      if (struct.clusteringKey != null) {
        oprot.writeFieldBegin(CLUSTERING_KEY_FIELD_DESC);
        oprot.writeString(struct.clusteringKey);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class KeyTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public KeyTupleScheme getScheme() {
      return new KeyTupleScheme();
    }
  }

  private static class KeyTupleScheme extends org.apache.thrift.scheme.TupleScheme<Key> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Key struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPartitionKey()) {
        optionals.set(0);
      }
      if (struct.isSetClusteringKey()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPartitionKey()) {
        oprot.writeString(struct.partitionKey);
      }
      if (struct.isSetClusteringKey()) {
        oprot.writeString(struct.clusteringKey);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Key struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.partitionKey = iprot.readString();
        struct.setPartitionKeyIsSet(true);
      }
      if (incoming.get(1)) {
        struct.clusteringKey = iprot.readString();
        struct.setClusteringKeyIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

