/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.flink.connectors.loghouse.service;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-03-10")
public class TrafficEnv implements org.apache.thrift.TBase<TrafficEnv, TrafficEnv._Fields>, java.io.Serializable, Cloneable, Comparable<TrafficEnv> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TrafficEnv");

  private static final org.apache.thrift.protocol.TField OPEN_FIELD_DESC = new org.apache.thrift.protocol.TField("Open", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField ENV_FIELD_DESC = new org.apache.thrift.protocol.TField("Env", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TrafficEnvStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TrafficEnvTupleSchemeFactory();

  public boolean Open; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String Env; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OPEN((short)1, "Open"),
    ENV((short)2, "Env");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // OPEN
          return OPEN;
        case 2: // ENV
          return ENV;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __OPEN_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.OPEN, new org.apache.thrift.meta_data.FieldMetaData("Open", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ENV, new org.apache.thrift.meta_data.FieldMetaData("Env", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TrafficEnv.class, metaDataMap);
  }

  public TrafficEnv() {
    this.Open = false;

    this.Env = "";

  }

  public TrafficEnv(
    boolean Open,
    java.lang.String Env)
  {
    this();
    this.Open = Open;
    setOpenIsSet(true);
    this.Env = Env;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TrafficEnv(TrafficEnv other) {
    __isset_bitfield = other.__isset_bitfield;
    this.Open = other.Open;
    if (other.isSetEnv()) {
      this.Env = other.Env;
    }
  }

  public TrafficEnv deepCopy() {
    return new TrafficEnv(this);
  }

  @Override
  public void clear() {
    this.Open = false;

    this.Env = "";

  }

  public boolean isOpen() {
    return this.Open;
  }

  public TrafficEnv setOpen(boolean Open) {
    this.Open = Open;
    setOpenIsSet(true);
    return this;
  }

  public void unsetOpen() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __OPEN_ISSET_ID);
  }

  /** Returns true if field Open is set (has been assigned a value) and false otherwise */
  public boolean isSetOpen() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __OPEN_ISSET_ID);
  }

  public void setOpenIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __OPEN_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getEnv() {
    return this.Env;
  }

  public TrafficEnv setEnv(@org.apache.thrift.annotation.Nullable java.lang.String Env) {
    this.Env = Env;
    return this;
  }

  public void unsetEnv() {
    this.Env = null;
  }

  /** Returns true if field Env is set (has been assigned a value) and false otherwise */
  public boolean isSetEnv() {
    return this.Env != null;
  }

  public void setEnvIsSet(boolean value) {
    if (!value) {
      this.Env = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case OPEN:
      if (value == null) {
        unsetOpen();
      } else {
        setOpen((java.lang.Boolean)value);
      }
      break;

    case ENV:
      if (value == null) {
        unsetEnv();
      } else {
        setEnv((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case OPEN:
      return isOpen();

    case ENV:
      return getEnv();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case OPEN:
      return isSetOpen();
    case ENV:
      return isSetEnv();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TrafficEnv)
      return this.equals((TrafficEnv)that);
    return false;
  }

  public boolean equals(TrafficEnv that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_Open = true;
    boolean that_present_Open = true;
    if (this_present_Open || that_present_Open) {
      if (!(this_present_Open && that_present_Open))
        return false;
      if (this.Open != that.Open)
        return false;
    }

    boolean this_present_Env = true && this.isSetEnv();
    boolean that_present_Env = true && that.isSetEnv();
    if (this_present_Env || that_present_Env) {
      if (!(this_present_Env && that_present_Env))
        return false;
      if (!this.Env.equals(that.Env))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((Open) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetEnv()) ? 131071 : 524287);
    if (isSetEnv())
      hashCode = hashCode * 8191 + Env.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TrafficEnv other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetOpen()).compareTo(other.isSetOpen());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOpen()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Open, other.Open);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetEnv()).compareTo(other.isSetEnv());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEnv()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Env, other.Env);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TrafficEnv(");
    boolean first = true;

    sb.append("Open:");
    sb.append(this.Open);
    first = false;
    if (!first) sb.append(", ");
    sb.append("Env:");
    if (this.Env == null) {
      sb.append("null");
    } else {
      sb.append(this.Env);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TrafficEnvStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TrafficEnvStandardScheme getScheme() {
      return new TrafficEnvStandardScheme();
    }
  }

  private static class TrafficEnvStandardScheme extends org.apache.thrift.scheme.StandardScheme<TrafficEnv> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TrafficEnv struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // OPEN
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.Open = iprot.readBool();
              struct.setOpenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ENV
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Env = iprot.readString();
              struct.setEnvIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TrafficEnv struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(OPEN_FIELD_DESC);
      oprot.writeBool(struct.Open);
      oprot.writeFieldEnd();
      if (struct.Env != null) {
        oprot.writeFieldBegin(ENV_FIELD_DESC);
        oprot.writeString(struct.Env);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TrafficEnvTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TrafficEnvTupleScheme getScheme() {
      return new TrafficEnvTupleScheme();
    }
  }

  private static class TrafficEnvTupleScheme extends org.apache.thrift.scheme.TupleScheme<TrafficEnv> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TrafficEnv struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetOpen()) {
        optionals.set(0);
      }
      if (struct.isSetEnv()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetOpen()) {
        oprot.writeBool(struct.Open);
      }
      if (struct.isSetEnv()) {
        oprot.writeString(struct.Env);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TrafficEnv struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.Open = iprot.readBool();
        struct.setOpenIsSet(true);
      }
      if (incoming.get(1)) {
        struct.Env = iprot.readString();
        struct.setEnvIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

