#!/bin/env python
# -*- coding:utf-8 -*-

#
#  Autogenerated by Storm-Streaming Topology
#
#  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from pyutil.program import metrics2 as metrics
from ss_lib.topology.util.bolt import CommonBolt

import gc, traceback, sys, time, os, threading, signal, logging, random, multiprocessing, ujson, json
import ss_lib.topology.util.subprocess_caller as process_caller


class {{bolt_name}}(CommonBolt):
    def init(self, conf, dsignal):
        """ bolt init function, you can add your initialization below.
        Args:
            conf : A dict type, the key/value is from bolt args configuration in the topology.yaml
            dsignal : DSignal object, maybe you just need use dsignal.lock class member
        
        Returns:
            no return
        """
        self.conf = conf
        self.dsignal = dsignal
        
        try:
            self.process_caller = process_caller.ProcessCaller(self.conf, desc=self.conf.get("bolt_name"))
        except Exception as e:
            logging.exception(e)

    def on_signal(self, data):
        """ signal callback function
        Args:
            data : A dict type, eg:{'cmd' : 'stop'}

        Returns:
            no return

        """
        try:
            ts = time.time()
            if data.get("cmd") == "stop":
                time.sleep(2)
                with self.dsignal.lock:
                    self.process_caller.stop() 
                logging.info("pid[%d] handle stop signal end, handle time:%f"%(os.getpid(), time.time() - ts))
            elif data.get("cmd") == "reload":
                with self.dsignal.lock:
                    logging.info("start to reload the bolt, wait dsignal_lock time:%f"%(time.time() - ts))
                    self.process_caller.restart()
                logging.info("handle reload signal end, handle time:%f"%(time.time() - ts))
            else :
                pass
        except Exception as e:
            logging.exception(e)

    def calc(self, tup, tup_type):
        """ add your logic here
        Args:
            tup : the stream data, a list type, eg:
              if the last bolt's output_fields:
                ["ut:uid", "gid", "gid:atype:atime:stream", "kt", "from_tup"], 
              the format of the tup is :
                ['12:1451376260', 3487133828, (3487302803, 202, 1408936076, '__feed__'), 1408936076, 0]
        Returns:
            res_list : A list type
              if the current bolt's output_fields is [c11,c21], you must return [[c11,c21]].
              if you want to emit more data at one time, you can return [[c11,c21],[c12, c22],[c13,c23], ...]

        """
        with self.dsignal.lock:
            req = {}
            req[tup_type] = tup
            ret_dict = self.process_caller.exec_task(req)
            return ret_dict.get("res", [])

{{bolt_name}}().run()

if __name__ == "__main__":
    pass
